builders:
  mangoBuilder:
    import: "package:mango_builder/mango_builder.dart"
    builder_factories: ["mangoBuilder"]
    build_extensions: {".html": [".html.dart"]}
    build_to: source
    auto_apply: root_package
