name: examples
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: jonahwilliams <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta:
  incremental_dom:
    path: ../incremental_dom
  mango:
    path: ../mango

dev_dependencies:
  mango_builder:
    path: ../mango_builder
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
