name: mango_compiler
description: A starting point for Dart libraries or applications.
version: 0.0.1
author: Jonah Williams <jonah.a.williams@outlook.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.5.1
